---
title: "Make Df"
author: "Brianne"
date: "4/22/2021"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/Brianne/Documents/San-Clemente-Biocrust-/")
```

```{r load libraries}
library(tidyverse)
```


```{r bulk data}
bulk <- read.csv("C:/Users/Brianne/OneDrive - San Diego State University (SDSU.EDU)/R WorkBooks/metagenomics/data/Ben_sci_taxon_rel_abund.csv")
bulk.metadata <- read.csv("C:/Users/Brianne/OneDrive - San Diego State University (SDSU.EDU)/R WorkBooks/metagenomics/data/metadata_bulk.csv")

bulk.genus <- bulk %>%  dplyr::select(genus, bulk1:bulk40)

bulk.genus <- aggregate(. ~ genus, transform(bulk.genus, genus = genus), sum)

# The first column is actually the row names
rownames(bulk.genus) <- bulk.genus$genus
bulk.genus$genus <- NULL
head(bulk.genus)
bulk.genus.transposed <- data.frame(t((bulk.genus)))
rownames(bulk.genus.transposed) <- colnames(bulk.genus)
colnames(bulk.genus.transposed) <- rownames(bulk.genus)

bulk.all <- as.data.frame(c(bulk.metadata, bulk.genus.transposed))
#bulk.all <- bulk.all %>% rename(Sample = ï..Sample)
bulk.all <- bulk.all[-c(1,23,34,40,45, 17, 30,9),]

bulk.genus.only <- bulk.all[-c(1:90)]
bulk.genus.sums.long <- gather(bulk.genus.only, genus, n, 1:1117)
bulk.genus.sums.long$n <- as.numeric(bulk.genus.sums.long$n)
bulk.sum_genus <- aggregate(n ~ genus, data=bulk.genus.sums.long, sum)

bulk.genera  <- bulk.sum_genus$genus [order (bulk.sum_genus$n, decreasing = TRUE)]
bulk.genera.order <- subset(bulk.sum_genus, genus %in% bulk.genera[1:200])

bulk.names <- bulk.genera.order$genus
bulk.name.use <- bulk.genus.only[names(bulk.genus.only) %in% bulk.names]
bulk <- data.frame(bulk.all[-c(91:1207)], bulk.name.use)

write.csv(bulk.all, "output/bulk_all.csv")
```


```{r bsc data}

all.taxa <- read.csv("C:/Users/Brianne/Documents/San-Clemente-Biocrust-/data/taxon_rel_abund_edited_Feb2021.csv")
metadata <- read.csv("C:/Users/Brianne/Documents/San-Clemente-Biocrust-/data/metadata.csv")
metadata <- metadata[c(1:24),]

bsc.genus <- all.taxa %>%  dplyr::select(genus, X1:X24)

# The first column is actually the row names
rownames(bsc.genus) <- bsc.genus$genus
bsc.genus$genus <- NULL
bsc.genus.transposed <- data.frame(t((bsc.genus)))
rownames(bsc.genus.transposed) <- colnames(bsc.genus)
colnames(bsc.genus.transposed) <- rownames(bsc.genus)

bsc.all <- as.data.frame(c(metadata, bsc.genus.transposed))
#bsc.all <- bsc.all %>% rename(Sample = ï..Sample)

bsc.genus.only <- bsc.all[-c(1:90)]
bsc.genus.sums.long <- gather(bsc.genus.only, genus, n, 1:940)
bsc.genus.sums.long$n <- as.numeric(bsc.genus.sums.long$n)
bsc.sum_genus <- aggregate(n ~ genus, data=bsc.genus.sums.long, sum)

bsc.genera  <- bsc.sum_genus$genus [order (bsc.sum_genus$n, decreasing = TRUE)]
bsc.genera.order <- subset(bsc.sum_genus, genus %in% bsc.genera[1:200])

bsc.names <- bsc.genera.order$genus
bsc.name.use <- bsc.genus.only[names(bsc.genus.only) %in% bsc.names]
bsc <- data.frame(metadata,bsc.name.use)
# bsc <- bsc %>% filter(site != "rc")

write.csv(bsc, "output/bsc_all.csv")
```

```{r macro and plants}
#####
macro <- read.csv("data/sci_bsc_18_19_20_editMarch2021.csv")
macro <- macro %>% filter(Sample.Year == "2018", Treatment != "wild")
macro$ID <- macro$ï..Plot
macro <- macro %>% group_by(Site, Treatment, Quad, ID)%>% summarize_at(vars(cyano:Total),list(mean = mean))
macro <- macro%>% rename_at(.vars = vars(ends_with("_mean")), .funs = funs(sub("[_]mean$", "", .)))
macro <- macro[-8]
# remove NAs 
which(is.na(macro), arr.ind=TRUE)
macro <- na.omit(macro)
write.csv(macro, "output/macro_cover.csv")

 #####
plants <- read.csv("data/all_plants_March2021edit.csv")
plants <- plants %>% filter(Year == 2018) 
plants$Cover <- as.numeric(plants$Cover)
ng.cov <- plants %>% filter(Funct.Gp == "ng") %>% mutate(ng.cov = mean(Cover))
plants <- merge(plants, ng.cov, all = TRUE)
nng.cov <- plants %>% filter(Funct.Gp == "nng") %>% mutate(nng.cov = mean(Cover))
plants <- merge(plants, nng.cov, all = TRUE)
nnf.cov <- plants %>% filter(Funct.Gp == "nnf") %>% mutate(nnf.cov = mean(Cover))
plants <- merge(plants, nnf.cov, all = TRUE)
nf.cov <- plants %>% filter(Funct.Gp == "nf") %>% mutate(nf.cov = mean(Cover))
plants <- merge(plants, nf.cov, all = TRUE)
plants[is.na(plants)] <- 0
plants$ID <- plants$ï..Ref

plants$Cover <- as.numeric(plants$Cover)
plants <- plants %>% pivot_wider(names_from = Code, values_from = Cover, values_fn = list(Cover = mean))

plants[is.na(plants)] <- 0

plants <- plants %>% group_by(Site, Treatment, Quad, ID) %>% summarize_at(vars(ng.cov:VIOPED),list(mean = mean))

plants <- plants %>% rename_at(.vars = vars(ends_with("_mean")), .funs = funs(sub("[_]mean$", "", .)))

# remove the same rows as macro (where there were NAs)

plants.rm <- plants[-c(206:208, 216:218, 225:228, 235:238),]

write.csv(plants.rm, "output/plants_all.csv")

```

Combine the datasets together in pairs. Make sure you natch the treatments and sites. May have to use merge() to do that 

Make Macro-Plant
```{r}

#plants is missing PGE burn 1 B, PGEB2C
macro_rm <- macro[-c(51,62),]
macro_plant <- data.frame(macro_rm, plants.rm)

write.csv(macro_plant, "output/macro_plant.csv")


```

Make Macro-BSC
```{r}
macro_short <- macro %>% dplyr::select(Site, Treatment, cyano, Lichen, Moss, Total) %>% 
    group_by(Site, Treatment) %>% summarize(cyano = mean(cyano), Lichen = mean(Lichen), Moss = mean(Moss), Total = mean(Total))

pgwburn <- data.frame(rbind(macro_short[3,],macro_short[3,],macro_short[3,],macro_short[3,]))
pgwcont <- data.frame(rbind(macro_short[4,],macro_short[4,],macro_short[4,],macro_short[4,]))
pgeburn <- data.frame(rbind(macro_short[1,],macro_short[1,],macro_short[1,],macro_short[3,]))
pgecont <- data.frame(rbind(macro_short[2,],macro_short[2,],macro_short[2,],macro_short[4,]))
rcburn <- data.frame(rbind(macro_short[5,],macro_short[5,],macro_short[5,],macro_short[5,]))
rccont <- data.frame(rbind(macro_short[6,],macro_short[6,],macro_short[6,],macro_short[6,]))

macro_short <-data.frame(rbind(pgwcont,pgwburn,pgecont,pgeburn,rccont,rcburn))
# double check to make sure the treatments and sites match 

macro_bsc <- data.frame(macro_short, bsc)

write.csv(macro_bsc, "output/macro_bsc.csv")
```

```{r make bsc macro }
bsc_macro <- bsc %>% 
    group_by(site, treatment) %>% summarize_at(vars(Methanosarcina:Microvirus),list(mean = mean))

n <- 40
pgwburn <- do.call("rbind", replicate(n, bsc_macro[3,], simplify = FALSE))
pgwcont <- do.call("rbind", replicate(n, bsc_macro[4,], simplify = FALSE))
pgeburn <- do.call("rbind", replicate(n, bsc_macro[1,], simplify = FALSE))
pgecont <-do.call("rbind", replicate(n, bsc_macro[2,], simplify = FALSE))
rcburn <- do.call("rbind", replicate(n, bsc_macro[5,], simplify = FALSE))

n <- 26 # to account for macro nas
rccont <- do.call("rbind", replicate(n, bsc_macro[6,], simplify = FALSE))
bsc_macro <- data.frame(rbind(pgecont,pgeburn,pgwcont,pgwburn,rccont,rcburn))

macro.2 <-  read.csv("data/sci_bsc_18_19_20_editMarch2021.csv")
macro.2 <- macro.2 %>% filter(Sample.Year == "2018", Treatment != "rx/wild")
macro.2$ID <- macro.2$ï..Plot
macro.2 <- macro.2 %>% group_by(Site, Treatment, Quad, ID)%>% summarize_at(vars(cyano:Total),list(mean = mean))
macro.2 <- macro.2 %>% rename_at(.vars = vars(ends_with("_mean")), .funs = funs(sub("[_]mean$", "", .)))
macro.2 <- macro.2[-8]
# remove NAs 
macro.2 <- na.omit(macro.2)


bsc_macro <- data.frame(bsc_macro, macro.2) #make sure treatments and sites match!
bsc_macro <- bsc_macro%>% rename_at(.vars = vars(ends_with("_mean")), .funs = funs(sub("[_]mean$", "", .)))

write.csv(bsc_macro, "output/bsc_macro.csv")
```

Make Macro-Bulk
```{r}
# remove RC because Ben did not sample RC use macro.3

bulk_long <- bulk %>% 
    group_by(site, treatment) %>% summarize_at(vars(Achromobacter:Zymomonas),list(mean = mean))


n <- 40

pgwburn <- do.call("rbind", replicate(n, bulk_long[3,], simplify = FALSE))
pgwcont <- do.call("rbind", replicate(n, bulk_long[4,], simplify = FALSE))
pgeburn <- do.call("rbind", replicate(n, bulk_long[1,], simplify = FALSE))
pgecont <-do.call("rbind", replicate(n, bulk_long[2,], simplify = FALSE))

bulk_long <- data.frame(rbind(pgecont, pgeburn, pgwcont, pgwburn))

macro.3 <- macro %>% filter(Site != "rc")

macro_bulk <- data.frame(macro.3, bulk_long)

macro_bulk <- macro_bulk %>% rename_at(.vars = vars(ends_with("_mean")), .funs = funs(sub("[_]mean$", "", .)))

write.csv(macro_bulk, "output/macro_bulk.csv")

```

Make Plant- BSC
```{r}

bsc.pg <- bsc %>% filter(site != "rc")
plants <- read.csv("data/all_plants.csv")
plants <- plants %>% filter(Year == 2018, Site != "RC") 
plants$Cover <- as.numeric(plants$Cover)
ng.cov <- plants %>% filter(Funct.Gp == "ng") %>% mutate(ng.cov = mean(Cover))
plants <- merge(plants, ng.cov, all = TRUE)
nng.cov <- plants %>% filter(Funct.Gp == "nng") %>% mutate(nng.cov = mean(Cover))
plants <- merge(plants, nng.cov, all = TRUE)
nnf.cov <- plants %>% filter(Funct.Gp == "nnf") %>% mutate(nnf.cov = mean(Cover))
plants <- merge(plants, nnf.cov, all = TRUE)
nf.cov <- plants %>% filter(Funct.Gp == "nf") %>% mutate(nf.cov = mean(Cover))
plants <- merge(plants, nf.cov, all = TRUE)
plants <- plants %>% pivot_wider(names_from = Code, values_from = Cover, values_fn = list(Cover = mean)) 
plants[is.na(plants)] <- 0
plants_short <- plants %>% group_by(Site, Treatment, Year) %>% summarize_at(vars(ng.cov:VIOPED),list(mean = mean))

pgwburn <- data.frame(rbind(plants_short[3,],plants_short[3,],plants_short[3,],plants_short[3,]))
pgwcont <- data.frame(rbind(plants_short[4,],plants_short[4,],plants_short[4,],plants_short[4,]))
pgeburn <- data.frame(rbind(plants_short[1,],plants_short[1,],plants_short[1,],plants_short[1,]))
pgecont <- data.frame(rbind(plants_short[2,],plants_short[2,],plants_short[2,],plants_short[2,]))

plants_short <- data.frame(rbind(pgwburn, pgwcont, pgeburn, pgecont))

write.csv(plants_short, "output/plants_short.csv")

bsc_plant <- data.frame(plants_short, bsc.pg)

write.csv(bsc_plant, "output/bsc_plant.csv")

bsc_short <- bsc.pg %>% group_by(site, treatment) %>% summarize_at(vars(Methanosarcina:Microvirus), list(mean = mean))

n <- 10

pgwburn <- do.call("rbind", replicate(n, bsc_short[3,], simplify = FALSE))
pgwcont <- do.call("rbind", replicate(n, bsc_short[4,], simplify = FALSE))
pgeburn <- do.call("rbind", replicate(n, bsc_short[1,], simplify = FALSE))
pgecont <-do.call("rbind", replicate(n, bsc_short[2,], simplify = FALSE))

bsc_short <- data.frame(rbind(pgeburn, pgecont, pgwburn, pgwcont))
plants <- read.csv("data/all_plants.csv")
plants <- plants %>% filter(Year == 2018, Site != "RC") 
plants$Cover <- as.numeric(plants$Cover)
ng.cov <- plants %>% filter(Funct.Gp == "ng") %>% mutate(ng.cov = mean(Cover))
plants <- merge(plants, ng.cov, all = TRUE)
nng.cov <- plants %>% filter(Funct.Gp == "nng") %>% mutate(nng.cov = mean(Cover))
plants <- merge(plants, nng.cov, all = TRUE)
nnf.cov <- plants %>% filter(Funct.Gp == "nnf") %>% mutate(nnf.cov = mean(Cover))
plants <- merge(plants, nnf.cov, all = TRUE)
nf.cov <- plants %>% filter(Funct.Gp == "nf") %>% mutate(nf.cov = mean(Cover))
plants <- merge(plants, nf.cov, all = TRUE)
plants <- plants %>% pivot_wider(names_from = Code, values_from = Cover, values_fn = list(Cover = mean)) 
plants[is.na(plants)] <- 0
plants$ID <- plants$ï..Ref
plants <-  plants %>% group_by(Site, Treatment, Year, ID) %>% summarize_at(vars(ng.cov:VIOPED),list(mean = mean))

plant_bsc <- data.frame(bsc_short, plants)
plant_bsc <- plant_bsc %>% rename_at(.vars = vars(ends_with("_mean")), .funs = funs(sub("[_]mean$", "", .)))

write.csv(plant_bsc, "output/plant_bsc.csv")
```

Make Plant-Bulk
```{r}

plant_bulk <- data.frame(plants, bulk)
plant_bulk <- plant_bulk %>% rename_at(.vars = vars(ends_with("_mean")), .funs = funs(sub("[_]mean$", "", .)))

write.csv(plant_bulk, "output/plant_bulk.csv")
```

Make BSC - Bulk

```{r}
bulk <- bulk %>% mutate_at(c(91:290), as.numeric)

bulk_short <- bulk %>% 
    group_by(site, treatment) %>% summarize_at(vars(Achromobacter:Zymomonas),list(mean = mean))

pgwburn <- data.frame(rbind(bulk_short[3,],bulk_short[3,],bulk_short[3,],bulk_short[3,]))
pgwcont <- data.frame(rbind(bulk_short[4,],bulk_short[4,],bulk_short[4,],bulk_short[4,]))
pgeburn <- data.frame(rbind(bulk_short[1,],bulk_short[1,],bulk_short[1,],bulk_short[3,]))
pgecont <- data.frame(rbind(bulk_short[2,],bulk_short[2,],bulk_short[2,],bulk_short[4,]))

bulk_short <- data.frame(rbind(pgwburn, pgwcont, pgeburn, pgecont))

bsc_bulk <- data.frame(bulk_short, bsc.pg)
write.csv(bsc_bulk, "output/bsc_bulk.csv")

```