---
title: "Plant Community"
author: "Brianne"
date: "3/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/Brianne/Documents/San-Clemente-Biocrust-/")
```

```{r load libraries}
library(tidyverse)
library(MASS)
library(lme4)
library(car)
library(emmeans)
library(multcomp)
library(ggpubr)
library(rcompanion)
library(calecopal)
library(MuMIn)
library(vegan)
library(pairwiseAdonis)
```

```{r plant cover community}
plants <- read.csv("data/all_plants_March2021edit.csv")
plants <- plants %>% filter(Year == 2018 | Year == 2019) 
plants$Cover <- as.numeric(plants$Cover)
plants$Cover[is.na(plants$Cover)] <-0
ng.cov <- plants %>% filter(Funct.Gp == "ng") %>% mutate(ng.cov = (Cover))
plants <- merge(plants, ng.cov, all = TRUE)
nng.cov <- plants %>% filter(Funct.Gp == "nng") %>% mutate(nng.cov = mean(Cover))
plants <- merge(plants, nng.cov, all = TRUE)
nnf.cov <- plants %>% filter(Funct.Gp == "nnf") %>% mutate(nnf.cov = mean(Cover))
plants <- merge(plants, nnf.cov, all = TRUE)
nf.cov <- plants %>% filter(Funct.Gp == "nf") %>% mutate(nf.cov = mean(Cover))
plants <- merge(plants, nf.cov, all = TRUE)
plants[is.na(plants)] <- 0
plants$Cover <- as.numeric(plants$Cover)
plants$Density <- as.numeric(plants$Density)
plants <- plants %>% 
  pivot_wider(names_from = Code, values_from = Cover, values_fn = list(Cover = sum))
plants <- plants %>% mutate_at(c(103:185), as.numeric)

#plants <- plants %>% group_by(Site, Treatment, ID, Quad, Year) %>% summarize_at(vars(ng.cov:VIOPED),list(mean = mean))

#plants <- plants %>% rename_at(.vars = vars(ends_with("_mean")), .funs = funs(sub("[_]mean$", "", .)))


```


This code will run a for loop to determine which genera varied with treatment. I haven't figure out how to do this in R yet but to figure out if there were any genera that differed, I called the list of genera with rownames(genera) then copired and pasted that and the p values from this fore loop into an excel sheet. Not very graceful, but it works..
```{r}
plants.only <- plants[c(103:185)]
metadata <- plants[c(1:102)]

for(i in plants.only){
  eq <- lm(i ~ metadata$Treatment)
  aov.p.value <- summary(aov(eq))[[1]]$'Pr(>F)'
  print(aov.p.value)
} 


ggplot(data = plants, aes(x = Treatment, y = FESSPP, fill = Treatment)) + geom_bar(stat = "identity")



```

```{r plant density}
plants.d <- read.csv("data/all_plants_March2021edit.csv")
plants.d <- plants.d %>% filter(Year == 2018 | Year == 2019,T_Year == 2017)
plants.d$Density <- as.numeric(plants.d$Density)
plants.d[is.na(plants.d)] <- 0
ng.den <- plants.d %>% filter(Funct.Gp == "ng") %>% mutate(ng.den = mean(Density))
plants.d <- merge(plants.d, ng.den, all = TRUE)
nng.den <- plants.d %>% filter(Funct.Gp == "nng") %>% mutate(nng.den = mean(Density))
plants.d <- merge(plants.d, nng.den, all = TRUE)
nnf.den <- plants.d %>% filter(Funct.Gp == "nnf") %>% mutate(nnf.den = mean(Density))
plants.d <- merge(plants.d, nnf.den, all = TRUE)
nf.den <- plants.d %>% filter(Funct.Gp == "nf") %>% mutate(nf.den = mean(Density))
plants.d <- merge(plants.d, nf.den, all = TRUE)
plants.d$ID <- plants.d$ï..Ref
plants.d <- plants.d %>% pivot_wider(names_from = Code, values_from = Density, values_fn = list(Density = mean))
plants.d[is.na(plants.d)] <- 0
plants.d <- plants.d %>% mutate_at(c(104:186), as.numeric)
plants.d[is.na(plants.d)] <- 0
#plants.d <- plants.d %>% group_by(Site, Treatment, Quad, ID, Year) %>% summarize_at(vars(ng.den:VIOPED),list(mean = mean))

#plants.d <- plants.d %>% rename_at(.vars = vars(ends_with("_mean")), .funs = funs(sub("[_]mean$", "", .)))

```

```{r}


plants.only.d <- plants.d[c(104:186)]
metadata.d <- plants.d[c(1:103)]

for(i in plants.only.d){
  eq <- lm(i ~ metadata.d$Treatment)
  aov.p.value <- summary(aov(eq))[[1]]$'Pr(>F)'
  print(aov.p.value)
} 

ggplot(data = plants.d, aes(x = Treatment, y = MAFOFO, fill = Treatment)) + geom_bar(stat = "identity")

```


```{r commmunity nmds}
plants.short <- read.csv("data/all_plants_March2021edit.csv")
plants.short <- plants.short %>% filter(T_Year == "2017", Year == 2019 | Year ==2018)
plants.short <- plants.short %>% dplyr::rename(ID = ï..Ref)
plants.short <- plants.short %>% 
  pivot_wider(names_from = Code, values_from = Cover, values_fn = list(Cover = sum))
plants.short[is.na(plants.short)] <- 0
plants.short <- plants.short %>% mutate_at(vars(cyanocover_2018:MALSPP), as.numeric)
plants.short[is.na(plants.short)] <- 0
plants.short <- plants.short %>% group_by(Site, Treatment, ID, Year) %>% summarize_at(vars(cyanocover_2018:MALSPP),list(mean = mean))
plants.short <- plants.short %>% rename_at(.vars = vars(ends_with("_mean")), .funs = funs(sub("[_]mean$", "", .)))

plants.only <- plants.short[c(91:173)]
str(plants.only)
metadata <- plants.short[c(1:90)]

plant.nmds <- metaMDS(plants.only, trace = FALSE,"bray", trymax = 100)
plant.nmds$stress 

# make the NMDS plot and analyze dissimilarities 

#build a data frame with NMDS coordinates and metadata 
MDS1 = plant.nmds$points[,1] # adds the points of the NMDS 1 dimmension
MDS2 = plant.nmds$points[,2] # adds the points of the NMDS 2 dimmension

NMDS = data.frame(MDS1 = MDS1, MDS2 = MDS2, treatment = plants.short$Treatment, site = plants.short$Site, year = plants.short$Year)# this builds a dataframe with the NMDS dimmensions, treatment, site, and burn year 
NMDS$year <- as.factor(NMDS$year)

pdf("figures/plant site nmds.pdf")
# make the NMDS plot
ggplot(NMDS, aes(x = MDS1, y = MDS2, col = site)) + geom_point() + 
  stat_ellipse() + theme_bw()
dev.off()

pdf("figures/plant treatment nmds.pdf")
ggplot(NMDS, aes(x = MDS1, y = MDS2, col = treatment)) + geom_point() + 
  stat_ellipse() + theme_bw()
dev.off()

pdf("figures/plant year nmds.pdf")
ggplot(NMDS, aes(x = MDS1, y = MDS2, col = year)) + geom_point() + 
  stat_ellipse() + theme_bw()
dev.off()

# determine if the differene is significant by doing a PERMANOVA
adonis(plants.only ~ Treatment, metadata) 
pairwise.adonis(plants.only,factors=metadata$Treatment)
pairwise.adonis(plants.only,factors=metadata$Site)
pairwise.adonis(plants.only,factors=metadata$Year)

env <- metadata[c(5:90)]
env.fit <- envfit(plant.nmds,env , permutations = 999, na.rm = TRUE)
env.fit$vectors
arrow <- data.frame(env.fit$vectors$arrows, R = env.fit$vectors$r, P = env.fit$vectors$pvals)
arrow$FG <-  rownames(arrow)
arrow.p <- filter(arrow, P<=0.05)
library(ggrepel)
pdf("figures/plant with env vectors.pdf")
ggplot(data=NMDS, aes(x = MDS1, y = MDS2)) + geom_point(data=NMDS, aes(MDS1, MDS2, shape =year),position=position_jitter(.1)) + stat_ellipse(aes(fill=treatment), alpha=.2,type='t',size =1, geom="polygon")+ theme_minimal()+ geom_segment(data=arrow.p, aes(x=0, y=0, xend=NMDS1, yend=NMDS2, color=FG), arrow=arrow(length=unit(.2, "cm")*arrow.p$R)) + geom_label_repel(data=arrow.p, aes(x=NMDS1, y=NMDS2,  label = FG),  label.padding = 0.1, label.size = 0.1, size =3, max.overlaps = 15) + theme(legend.position = "none")
dev.off()


## do it again but remove the year specific values 

arrow.p.2 <- arrow.p[-c(7,8,14:17, 19,20, 25:28),]
pdf("figures/plant nmds 2.pdf")
ggplot(data=NMDS, aes(x = MDS1, y = MDS2)) + geom_point(data=NMDS, aes(MDS1, MDS2, shape =year),position=position_jitter(.1)) + stat_ellipse(aes(fill=treatment), alpha=.2,type='t',size =1, geom="polygon")+ theme_minimal()+ geom_segment(data=arrow.p.2, aes(x=0, y=0, xend=NMDS1, yend=NMDS2, color=FG), arrow=arrow(length=unit(.2, "cm")*arrow.p$R)) + geom_label_repel(data=arrow.p.2, aes(x=NMDS1, y=NMDS2,  label = FG),  label.padding = 0.1, label.size = 0.1, size =3, max.overlaps = 15) + theme(legend.position = "none")
dev.off()

```