---
title: "Plant Cover"
author: "Brianne"
date: "3/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/Brianne/Documents/San-Clemente-Biocrust-/")
```

```{r load libraries}
library(tidyverse)
library(MASS)
library(lme4)
library(car)
library(emmeans)
library(multcomp)
library(ggpubr)
library(predictmeans)
library(lattice)
```


```{r load data}
data <- read.csv("data/all_plants_March2021edit.csv")
data <- data %>% filter(Year == 2018 | Year == 2019)
data$Cover <- as.numeric(data$Cover)
qqnorm(data$Cover)
data$Cover.log <- log(data$Cover)
boxplot.stats(data$Cover)$out
boxplot.stats(data$Cover.log)$out
data$Plot <- data$ï..Ref
data$Year <- as.factor(data$Year)
str(data)


```


```{r cover}

data$cover.plus.1 <- data$Cover+1
data$Cover.log <- log10(data$cover.plus.1)
bestmod.log <- lmer(Cover.log ~ Treatment + Year + Site + Funct.Gp + (1|Plot), data = data, REML=FALSE)
summary(bestmod.log)
Anova(bestmod.log)
residplot(bestmod.log)

boxplot(Cover.log ~ Treatment, data = data)

```


```{r}
#Tukey Post-Hoc Test 

summary(glht(bestmod.log, linfct = mcp(Treatment = "Tukey")))
summary(glht(bestmod.log, linfct = mcp(Year = "Tukey"))) # <2e-16
summary(glht(bestmod.log, linfct = mcp(Site= "Tukey"))) 
summary(glht(bestmod.log, linfct = mcp(Funct.Gp= "Tukey"))) 

```

```{r native grass cover}

bestmod.log <- lmer(Cover.log ~ FireType + Year + Site + (1|Plot), data = data %>% filter(Funct.Gp == "ng"), REML=FALSE)
summary(bestmod.log)
Anova(bestmod.log)

summary(glht(bestmod.log, linfct = mcp(FireType = "Tukey")))
summary(glht(bestmod.log, linfct = mcp(Year = "Tukey"))) # <2e-16
summary(glht(bestmod.log, linfct = mcp(Site= "Tukey"))) 

```

```{r native forb cover}

bestmod.log <- lmer(Cover ~ FireType + Site + Year + (1|Plot), data = data %>% filter(Funct.Gp == "nf"), REML=FALSE)
summary(bestmod.log)
Anova(bestmod.log)

summary(glht(bestmod.log, linfct = mcp(FireType = "Tukey")))
summary(glht(bestmod.log, linfct = mcp(Year = "Tukey"))) # <2e-16
summary(glht(bestmod.log, linfct = mcp(Site= "Tukey")))

plot(log(Cover) ~ Treatment, data = data %>% filter(Funct.Gp == "nf", Year == "2019"))

```
```{r nonnative grass cover}

bestmod.log <- lmer(Cover.log ~ FireType + Year + Site + (1|Plot), data = data %>% filter(Funct.Gp == "nng"), REML=FALSE)
summary(bestmod.log)
Anova(bestmod.log)

summary(glht(bestmod.log, linfct = mcp(FireType = "Tukey")))
summary(glht(bestmod.log, linfct = mcp(Year = "Tukey"))) # <2e-16
summary(glht(bestmod.log, linfct = mcp(Site= "Tukey"))) 

```

```{r nonnative forb cover}

bestmod.log <- lmer(Cover ~ FireType + Site + (1|Plot), data = data %>% filter(Funct.Gp == "nnf", Year == "2019"), REML=FALSE)
summary(bestmod.log)
Anova(bestmod.log)

summary(glht(bestmod.log, linfct = mcp(FireType = "Tukey")))
summary(glht(bestmod.log, linfct = mcp(Year = "Tukey"))) # <2e-16
summary(glht(bestmod.log, linfct = mcp(Site= "Tukey"))) 

```

```{r density}
data$Density <- as.numeric(data$Density)
data$density.plus.1 <- data$Density+1
data$density.log <- log10(data$density.plus.1)
bestmod.log <- lmer(density.log ~ Treatment + Year + Site + (1|Plot), data = data, REML=FALSE)
summary(bestmod.log)
Anova(bestmod.log)
residplot(bestmod.log)

boxplot(density.log ~ Treatment, data = data)

```


```{r}
#Tukey Post-Hoc Test 

summary(glht(bestmod.log, linfct = mcp(Treatment = "Tukey")))
summary(glht(bestmod.log, linfct = mcp(Year = "Tukey")))
summary(glht(bestmod.log, linfct = mcp(Site= "Tukey")))
```

```{r native grass density}

bestmod.log <- lmer(density.log ~ Treatment + Year + Site + (1|Plot), data = data %>% filter(Funct.Gp == "ng"), REML=FALSE)
summary(bestmod.log)
Anova(bestmod.log)

summary(glht(bestmod.log, linfct = mcp(Treatment = "Tukey")))
summary(glht(bestmod.log, linfct = mcp(Year = "Tukey"))) # <2e-16
summary(glht(bestmod.log, linfct = mcp(Site= "Tukey"))) 

```
```{r native forb density}

bestmod.log <- lmer(density.log ~ Treatment + Site + (1|Plot), data = data %>% filter(Funct.Gp == "nf"), REML=FALSE)
summary(bestmod.log)
Anova(bestmod.log)

summary(glht(bestmod.log, linfct = mcp(Treatment = "Tukey")))
summary(glht(bestmod.log, linfct = mcp(Year = "Tukey"))) # <2e-16
summary(glht(bestmod.log, linfct = mcp(Site= "Tukey"))) 

```
```{r nonnative grass density}

bestmod.log <- lmer(density.log ~ Treatment + Year + Site + (1|Plot), data = data %>% filter(Funct.Gp == "nng"), REML=FALSE)
summary(bestmod.log)
Anova(bestmod.log)

summary(glht(bestmod.log, linfct = mcp(Treatment = "Tukey")))
summary(glht(bestmod.log, linfct = mcp(Year = "Tukey"))) # <2e-16
summary(glht(bestmod.log, linfct = mcp(Site= "Tukey"))) 

```

```{r nonnative forb density}

bestmod.log <- lmer(density.log ~ Treatment + Year + Site + (1|Plot), data = data %>% filter(Funct.Gp == "nnf"), REML=FALSE)
summary(bestmod.log)
Anova(bestmod.log)

summary(glht(bestmod.log, linfct = mcp(Treatment = "Tukey")))
summary(glht(bestmod.log, linfct = mcp(Year = "Tukey"))) # <2e-16
summary(glht(bestmod.log, linfct = mcp(Site= "Tukey"))) 

```

```{r}

summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=TRUE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    datac <- rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}


df2 <- summarySE(data, measurevar = "Cover", groupvars=c("FireType", "Year"))
head(df2)

df2$Year <- as.numeric(df2$Year)

pdf("figures/plantcover.pdf")
ggplot(data = df2, aes(x = FireType, y = Cover, fill = FireType)) +
  geom_bar(sta = "identity") + 
  geom_errorbar(aes(ymin=(Cover - se), ymax=(Cover+se)), width=.2,
                 position=position_dodge(0.05)) + theme_bw()+ facet_wrap(.~ as.factor(Year)) + ggtitle("All Plant Cover") +  scale_fill_manual(values = cal_palette("superbloom3"))

dev.off()


df2 <- summarySE(data %>% filter(Funct.Gp == "ng"), measurevar = "Cover", groupvars=c("FireType", "Year"))
ggplot(data = df2, aes(x = FireType, y = Cover, fill = FireType)) +
  geom_bar(sta = "identity") + 
  geom_errorbar(aes(ymin=(Cover-se), ymax=(Cover+se)), width=.2,
                 position=position_dodge(0.05)) + theme_bw()+ facet_wrap(.~ as.factor(Year))+ ggtitle("Native Grass Cover") + scale_fill_manual(values = cal_palette("superbloom3"))

df2 <- summarySE(data %>% filter(Funct.Gp == "nng"), measurevar = "Cover", groupvars=c("FireType", "Year"))
ggplot(data = df2, aes(x = FireType, y = Cover, fill = FireType)) +
  geom_bar(sta = "identity") + 
  geom_errorbar(aes(ymin=(Cover-se), ymax=(Cover+se)), width=.2,
                 position=position_dodge(0.05)) + theme_bw()+ facet_wrap(.~ as.factor(Year))+ ggtitle("NonNative Grass Cover") + scale_fill_manual(values = cal_palette("superbloom3"))

df2 <- summarySE(data %>% filter(Funct.Gp == "nnf"), measurevar = "Cover", groupvars=c("FireType", "Year"))
ggplot(data = df2, aes(x = FireType, y = Cover, fill = FireType)) +
  geom_bar(sta = "identity") + 
  geom_errorbar(aes(ymin=(Cover-se), ymax=(Cover+se)), width=.2,
                 position=position_dodge(0.05)) + theme_bw()+ facet_wrap(.~ as.factor(Year))+ ggtitle("NonNative Forb Cover")+ scale_fill_manual(values = cal_palette("superbloom3"))

df2 <- summarySE(data %>% filter(Funct.Gp == "nf"), measurevar="Cover", groupvars=c("FireType", "Year"))
ggplot(data = df2, aes(x = FireType, y = Cover, fill = FireType)) +
  geom_bar(sta = "identity") + 
  geom_errorbar(aes(ymin=(Cover-se), ymax=(Cover+se)), width=.2,
                 position=position_dodge(0.05)) + theme_bw()+ facet_wrap(.~ as.factor(Year))+ ggtitle("Native Forb Cover")+ scale_fill_manual(values = cal_palette("superbloom3"))



df2 <- data_summary(data, varname="Density", 
                    groupnames=c("Treatment", "Year"))
df2$Year <- as.numeric(df2$Year)

pdf("figures/plantdensity.pdf")
ggplot(df2, aes(x=Year, y=Density, group=Treatment, fill=Treatment)) + 
  geom_bar(sta = "identity") + 
  geom_errorbar(aes(ymin=(Density), ymax=(Density+sd)), width=.2,
                 position=position_dodge(0.05)) + theme_bw() + 
  facet_grid(. ~ Treatment) + 
  scale_x_continuous(breaks = 1:2,
    labels = c("2018", "2019")) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")
dev.off()

```

```{r}

data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}


df2 <- data_summary(data, varname="Cover", 
                    groupnames=c("Funct.Gp", "Treatment", "Year"))
head(df2)

# with year as a continuous variable 
df2$Year <- as.numeric(df2$Year)

pdf("figures/plant functional group cover.pdf")
ggplot(df2 %>% filter(Funct.Gp != "UNK" & Funct.Gp != "ns" & Funct.Gp != "nns"), aes(x=Year, y=Cover, group=Treatment, color=Treatment)) + 
  geom_line() + 
  geom_point()+ 
  geom_errorbar(aes(ymin=Cover -sd , ymax=Cover+sd), width=.2,
                 position=position_dodge(0.05)) + theme_bw() + 
  facet_grid(Funct.Gp ~ Treatment) + 
  scale_x_continuous(breaks = 1:2,
    labels = c("2018", "2019")) +
  theme(legend.position = "none")
dev.off()

df2 <- data_summary(data, varname="Density", 
                    groupnames=c("Funct.Gp", "Treatment", "Year"))
head(df2)

df2$Year <- as.numeric(df2$Year)
ggplot(df2 %>% filter(Funct.Gp == "ng"), aes(x=Year, y=Cover, group=Treatment, color=Treatment)) + 
  geom_line() + 
  geom_point()+ 
  geom_errorbar(aes(ymin=Cover -sd , ymax=Cover+sd), width=.2,
                 position=position_dodge(0.05)) + theme_bw() +
  scale_x_continuous(breaks = 1:2,
    labels = c("2018", "2019")) +
  facet_grid(.~Year) +
  theme(legend.position = "none")


# with year as a continuous variable 
df2$Year <- as.numeric(df2$Year)

pdf("figures/plant functional group density.pdf")
ggplot(df2 %>% filter(Funct.Gp != "UNK" & Funct.Gp != "ns" & Funct.Gp != "nns"), aes(x=Year, y=Density, group=Treatment, color=Treatment)) + 
  geom_line() + 
  geom_point()+ 
  geom_errorbar(aes(ymin=Density -sd , ymax=Density+sd), width=.2,
                 position=position_dodge(0.05)) + theme_bw() + 
  facet_grid(Funct.Gp ~ Treatment) + 
  scale_x_continuous(breaks = 1:2,
    labels = c("2018", "2019")) +
  theme(legend.position = "none")
dev.off()

```
